apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-{{ $.Values.ingress.environment }}-adminui20"
spec:
{{- if eq $.Values.ingress.environment "prod" }}
  replicas: 3
{{- else }}
  replicas: 1
{{- end }}
  minReadySeconds: 35
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
        maxSurge: 30%
  template:
    metadata:
      creationTimestamp: null
      labels:
        chart: {{ .Chart.Name }}
        app: "{{.Release.Name}}-adminui20"
        app.kubernetes.io/name: adminui20
        app.kubernetes.io/instance: "{{.Release.Name}}-adminui20"
        app.kubernetes.io/tier: admin-frontend
        app.kubernetes.io/part-of: valuead
        app.kubernetes.io/managed-by: git
    spec:
      containers:
      - name: adminui20
        image: "{{ .Values.adminui20.image.repository }}:{{ .Values.adminui20.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodegroup
                operator: In
                values:
                - vastack
{{- if eq $.Values.ingress.environment "prod" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - "{{.Release.Name}}-adminui20"
              topologyKey: "kubernetes.io/hostname"
{{- end }}
status: {}
